code: "EnvironmentalRisk"
nameId: "Environmental Risk"
descriptionId: "Environmental Risk"
groupCode: "Operations & Reliability"
mustImpact: true
investmentApplicability: "Optional"
assetTypes: []
measures:
- code: "EnvironmentalRisk"
  nameId: "Environmental Risk"
  valueMeasureCode: "EnvironmentalRisk"
  sequence: 21
questionnaires:
- code: "Automated Risk Mitigation-EnvironmentalRisk-O"
  nameId: "Automated Risk Mitigation"
  descriptionId: "EnvironmentalRisk Automated Mitigation"
  isBaseline: false
  isDefault: true
  allowMeasureItemDuration: true
  prompts: []
  formulas:
  - measureCode: "EnvironmentalRisk"
    consequenceClassName: "RiskConsequenceAutomaticOutcome"
    likelihoodClassName: "RiskLikelihoodAutomaticOutcome"
- code: "Manual Risk-EnvironmentalRisk-B"
  nameId: "Manual Risk"
  descriptionId: "Environmental Risk"
  isBaseline: true
  isDefault: true
  allowMeasureItemDuration: true
  prompts:
  - measurePromptCode: "ManualRiskConsequence"
    sequence: 32
  - measurePromptCode: "ManualRiskProbability"
    sequence: 104
  - measurePromptCode: "Rationale"
    sequence: 170
  formulas:
  - measureCode: "EnvironmentalRisk"
    consequenceClassName: "RiskConsequenceManual"
    likelihoodClassName: "RiskLikelihoodManual"
- code: "Manual Risk-EnvironmentalRisk-O"
  nameId: "Manual Risk"
  descriptionId: "Environmental Risk"
  isBaseline: false
  isDefault: false
  allowMeasureItemDuration: true
  prompts:
  - measurePromptCode: "ManualRiskConsequence"
    sequence: 48
  - measurePromptCode: "ManualRiskProbability"
    sequence: 120
  formulas:
  - measureCode: "EnvironmentalRisk"
    consequenceClassName: "RiskConsequenceManual"
    likelihoodClassName: "RiskLikelihoodManual"
