code: "EnvironmentalRiskExposureFactor"
nameId: "Environmental Risk Exposure Factor"
descriptionId: "Exposure Factor (decimal proportion). If left blank, a factor of 1.0\
  \ will be used."
type: "Number"
isMultiline: false
isCloneable: true
numberDecimals: 7
maximumNumber: 10
listItems: []
